"""update models

Revision ID: 20772350a7e4
Revises: b62eab571245
Create Date: 2024-10-22 19:14:25.562235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20772350a7e4'
down_revision = 'b62eab571245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('minutes_to_complete',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('bio',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('bio',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('_password_hash')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('minutes_to_complete',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('instructions',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
